[platformio]
build_dir = build

[env:ATmega4809]
platform = atmelmegaavr
board = ATmega4809
framework = arduino

board_build.f_cpu = 16000000L

; MegaCoreX board options
board_hardware.oscillator = internal
board_hardware.uart = no_bootloader

; SerialUPDI programmer (cheap USB-UART adapter + 4k7 resistor)
upload_protocol = serialupdi
upload_speed = 115200
upload_flags =
    --tool
    uart
    --device
    atmega4809

; Atmel-ICE alternative:
; upload_protocol = atmelice_updi

build_flags =
    -DF_CPU=16000000L
    -DARDUINO_AVR_ATmega4809